Add Auto-correction Confidence settings
openboard-team/openboard pull request #695
Opened 2022-08-29 21:23 UTC by Pkshields

Hello!

This PR adds an Auto-correction Confidence option, letting the user configure how aggressive OpenBoard is with it's auto-correction of typos.

When using OpenBoard, I noticed that the keyboard was very good at coming up with fixes for my typos, but it didn't always auto-correct them for me. Instead I need to select the correction manually from the suggestions bar. This lead to me needing to slow down my typing, when I would be more than happy for OpenBoard to just insert the correction for me itself.

While looking into the issue, submitted under #687, it was noticed that almost all the functionality to achieve what I was looking for was already included within OpenBoard, it just wasn't currently in use. This PR is essentially just wiring up the existing auto-correct aggression levels within the codebase to a new configuration option.

The new auto-correct confidence setting defaults to "modest", which is the existing confidence level in use in OpenBoard.

Screenshots:
[New "Auto-correct confidence" setting](https://user-images.githubusercontent.com/49100076/187300081-b4611e81-34fd-4268-b2a8-ca2e7bce60b1.png)
[Available confidence levels](https://user-images.githubusercontent.com/49100076/187300295-b1785a8f-0d21-4e8a-a884-e2b031e20bdc.png)
[Setting is disabled when auto-correct is disabled](https://user-images.githubusercontent.com/49100076/187300364-069495dc-329d-4884-9698-a952cbf407f2.png)

Note: The PR also removes an auto-correction upgrade method, which I _believe_ came from the AOSP keyboard and has never been run on OpenBoard. To me, it would look confusing for this method to still be in the code when this new setting is available, so I removed it.

Thanks!

2022-12-13 14:34 UTC, MajeurAndroid commented
This looks really good ! Thanks. 
I commented something to address before I can merge this.

2022-12-13 21:25 UTC, Pkshields commented
Appreciate you taking a look!

The Modest auto complete setting looks to be working for me on this branch, when testing on my Pixel 5X. [I've recorded a video to show you it in action for me here](https://user-images.githubusercontent.com/49100076/207445742-d4d4eb1c-e508-421c-ad36-0713209e157c.mp4).

Is there anything missing in how I'm testing this here? Other than changing the confidence levels, I'm using an otherwise clean install of OpenBoard in that video.

2022-12-14 12:56 UTC, MajeurAndroid commented
Ok got it, indeed it works because of index definition in /app/src/main/res/values/config-auto-correction-thresholds.xml
But still, all three arrays should be synced, here index 0 is never used.
Could you fix this so we can merge this ? Thanks

2022-12-14 13:02 UTC, Pkshields commented
Yes, I can take another look at the arrays this evening.

Just to keep myself right, did you put a comment directly on that file yesterday? If you I'm not seeing it - the review might be sitting as pending. I've had that happen a few times on GitHub before.

2022-12-14 21:20 UTC, MajeurAndroid requested changes

2022-12-17 13:01 UTC, merged